In [1]:
import pandas as pd
import numpy as np
import nltk
df = pd.read_csv('../data/press_all.csv')

## Pre processing

In [2]:
df

,id,siren,url_article,title,text
0,0,572067684,http://www.autoactu.com/?page=2&id_actu=24240&...,autoactu.com - l'information automobile profes...,Bosch recrute des diplômés hautement qualifi...
1,1,790503973,http://www.ouest-france.fr/bretagne/lannion-22...,You have been blocked,Please enable JS and disable any ad blocker
2,2,433977980,http://www.businesswire.fr/news/fr/20160308006...,Axway s'associe à Navitas pour accompagner la ...,NaN
3,3,495232373,http://www.next-finance.net/Sofimac-Partners-a...,Marchés Privés - Sofimac Partners apporte 450 ...,Présent au capital de cette jeune entreprise ...
4,4,572050169,http://rss.usinenouvelle.com/~r/a-la-une/~3/Gs...,"Les finances dans le vert, Latécoère veut mode...",\n\n\n\n \n\nIdentifiez-vous\n L'Usine Aéro P...
...,...,...,...,...,...
76509,76509,510050461,https://www.lejsl.com/edition-bresse/2019/10/1...,Sornay | Un salarié prend la succession de Lec...,JOURNAL DE SAÔNE ET LOIRE Conditions généra...
76510,76510,445720717,https://abonne.lunion.fr/id102153/article/2019...,NaN,NaN
76511,76511,480012277,https://www.lemondedudroit.fr/deals/66470-jean...,Jeantet conseille Formel D - LE MONDE DU DROIT...,UTILISATION DES COOKIES : en poursuivant votr...
76512,76512,414819409,http://www.leparisien.fr/val-de-marne-94/ile-d...,"Ile-de-France : à Villeneuve-Saint-Georges, le...","« S'ils veulent nous virer, qu'ils le fassent..."
76513,76513,434004198,https://www.ladepeche.fr/2019/10/15/montauban-...,Montauban : les salariés de la plateforme Téré...,"Ce mardi, à 11 heures, 15 salariés de la plat..."

In [9]:
%%time
preprocessing(df['text'][0])
df['text'][0]

filter
to lower
extract
delete
CPU times: user 23.5 ms, sys: 0 ns, total: 23.5 ms
Wall time: 25.5 ms

"  Bosch recrute des diplômés hautement qualifiés en informatique mais très peu en France.  Bosch veut embaucher 14 000 jeunes diplômés en 2016. Pour près des deux tiers des postes qu’il compte créer, le groupe allemand cherche principalement des profils hautement qualifiés spécialisés dans l’informatique, des développeurs de logiciels pour des applications Web ou pour des systèmes de capteurs embarqués. Parmi ces embauches, 3 500 seront réalisées en Inde, 2 500 en Chine, 2 100 en Allemagne, et seulement 120 en France. L'entreprise emploie déjà plus de 15 000 développeurs de logiciels aujourd'hui. Elle emploie 375 000 personnes dans le monde, dont 132 000 en Allemagne, soit environ 17 600 personnes de plus qu’en 2014.Xavier Champagne \n\nInformations Légales\nConditions générales d'utilisation\nContacts\nDevenir annonceur\nVotre avis nous intéresse\n\n"

In [ ]:
#Replace NAN with ''

In [10]:
import re
import contractions
import string
import multiprocessing
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize 
import nltk
df = df.fillna("")

# Tokenize text
def preprocessing(text):
    # Remove stop words
    print("filter")
    word_list =  word_tokenize(text) 
    filtered_words = [word for word in word_list if word not in stopwords.words('english')]
    text = ' '.join(filtered_words)
    # To lowercase 
    print('to lower')
    text = text.lower()
    # Expand contractions
    print('extract')
    text = contractions.fix(text)
    # Delete punctuation 
    print('delete')
    translator = str.maketrans('', '', string.punctuation)
    text = text.translate(translator)
    return text
#df['text'] = df.apply(lambda row: preprocessing(row['text']), axis=1)
#df

In [ ]:
# Check average length of article 
df['length'] = df.text.apply(lambda x: len(x))
max_ = df.length.max()
print("Max: {}".format(max_))
min_ = df.length.min()
print("Min: {}".format(min_))
mean = df.length.mean()
print("Mean: {}".format(mean))

In [41]:
#Delete all articles with length 0 
# Get names of articles with length 0
indexNames = df[ df['length'] == 0 ].index

# Delete these row indexes from dataFrame
df.drop(indexNames , inplace=True)
df

,siren,legal_name,id,url_article,corpus,length
0,419838529,IPSEN,8,http://www.boursier.com/actions/actualites/new...,"[Ipsen, lorgne, les, peptides, de, PeptiMimesis]",6
1,419838529,IPSEN,2894,http://www.boursier.com/actions/actualites/new...,"[Ipsen, :, accord, important, avec, Probi, pub...",293
2,419838529,IPSEN,3057,http://www.boursier.com/actions/actualites/new...,"[La, médecine, générale, d'Ipsen, en, panne, a...",330
3,419838529,IPSEN,4208,http://www.cerclefinance.com/default.asp?pub=v...,"[Bourse, en, ligne, :, Information, boursiere,...",16
4,419838529,IPSEN,5284,http://www.cerclefinance.com/default.asp?pub=v...,"[Bourse, en, ligne, :, Information, boursiere,...",16
...,...,...,...,...,...,...
495,395030844,SANOFI,41863,https://www.lemondedudroit.fr/deals/57157-clif...,"[Clifford, Chance, conseil, de, banques, sur, ...",21
496,395030844,SANOFI,42528,https://www.lesechos.fr/industrie-services/pha...,"[Sanofi, fragilisé, par, le, recul, de, son, a...",497
497,395030844,SANOFI,43721,https://www.lesechos.fr/industrie-services/pha...,"[Sanofi, prépare, son, entrée, sur, le, marché...",579
498,395030844,SANOFI,43756,https://www.mypharma-editions.com/sanofi-le-do...,"[», Sanofi, :, le, Docteur, Jacques, Volckmann...",930
499,395030844,SANOFI,44862,http://www.boursier.com/actualites/reuters/san...,"[Sanofi, confiant, de, retrouver, de, solides,...",552

In [2]:
import pandas as pd
df_mapping = pd.read_csv('../data/siren_name_map.csv')

In [3]:
df_mapping

           siren            legal_name
0      419838529                 IPSEN
1      813883964          PEPTIMIMESIS
2      572060333                MERSEN
3      542104245       BANQUE PALATINE
4      399258755       SPIE OPERATIONS
...          ...                   ...
30173  834289373  LAGARDERE MEDIA NEWS
30174  813956265   E-VALLEY SERVICES 2
30175  440088938        SENVION FRANCE
30176  510050461  LECUELLE ELECTRICITE
30177  491668992       FORMEL D FRANCE

[30178 rows x 2 columns]

In [4]:
mapping_dict = df_mapping.to_dict()

In [8]:
from collections import defaultdict
mapping_dict = defaultdict(str)
for i,row in df_mapping.iterrows():
    mapping_dict[row.siren] = row.name

In [ ]:
import fasttext
model = fasttext.load_model("../data/pretrained-fasttext/cc.fr.300.bin")